# Generated by Django 6.0 on 2026-07-04 22:18

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("settings", "0006_alter_settings_admin_channel_ids_and_more")]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="balls_slash_name",
            field=models.TextField(
                default="balls",
                help_text='Overrides "/balls" slash command',
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z0-9-_']{1,32}$"),
                        message="Invalid slash command name. Must not contain spaces, caps, or some special chars.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="collectible_name",
            field=models.TextField(
                default="countryball",
                help_text="The singular name of your collectible",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z0-9-_']{1,32}$"),
                        message="Invalid slash command name. Must not contain spaces, caps, or some special chars.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="plural_collectible_name",
            field=models.TextField(
                default="countryballs",
                help_text="The plural name of your collectible",
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z0-9-_']{1,32}$"),
                        message="Invalid slash command name. Must not contain spaces, caps, or some special chars.",
                    )
                ],
            ),
        ),
    ]
